controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JoinTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_position_controller:
      type: position_controllers/JointPositionController 

joint_position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position


